services:
  - type: web
    name: vpm-bot
    runtime: node
    buildCommand: npm install && npm rebuild canvas --update-binary || true
    startCommand: node index.js
    envVars:
      - key: NODE_VERSION
        value: 18.20.0
